### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by smileycreations15** [MCloverz/ScratchBux#1]
Can you transfer the repository to me (use the settings tab)? You will still have write access.

**Comment by smileycreations15** [comment]
@MCloverz Is this fixed?

**Comment by MCloverz** [comment]
I did. I'll try again.

**Comment by smileycreations15** [comment]
> I did. I'll try again.

Ok. Go to the settings tab, scroll down and click transfer repository.

**Comment by MCloverz** [comment]
> > I did. I'll try again.
> 
> Ok. Go to the settings tab, scroll down and click transfer repository.

I know how to do it, it says transfer in progress.

**Comment by smileycreations15** [comment]
> > > I did. I'll try again.
> > 
> > 
> > Ok. Go to the settings tab, scroll down and click transfer repository.
> 
> I know how to do it, it says transfer in progress.

Can you send the screenshot to github?

**Comment by smileycreations15** [comment]
> > > I did. I'll try again.
> > 
> > 
> > Ok. Go to the settings tab, scroll down and click transfer repository.
> 
> I know how to do it, it says transfer in progress.

Also while it says that do not close the tab.

**Comment by MCloverz** [comment]
> > > > I did. I'll try again.
> > > 
> > > 
> > > Ok. Go to the settings tab, scroll down and click transfer repository.
> > 
> > 
> > I know how to do it, it says transfer in progress.
> 
> Can you send the screenshot to github?

![image](https://user-images.githubusercontent.com/49820780/59542045-1b559b80-8f58-11e9-88d5-86454aec867f.png)

**Comment by smileycreations15** [comment]
> > > > > I did. I'll try again.
> > > > 
> > > > 
> > > > Ok. Go to the settings tab, scroll down and click transfer repository.
> > > 
> > > 
> > > I know how to do it, it says transfer in progress.
> > 
> > 
> > Can you send the screenshot to github?
> 
> ![image](https://user-images.githubusercontent.com/49820780/59542045-1b559b80-8f58-11e9-88d5-86454aec867f.png)

Thanks for the verification. Also github auto-updates comment lists.

**Comment by smileycreations15** [comment]
@MCloverz Please close all tabs that have this repository open, and do not send any other messages in this repo.

**Comment by smileycreations15** [comment]
@MCloverz You can open the tabs now. I needed to approve the transfer that was the whole issue.
